export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    PROFILE: '/auth/profile',
    LOGOUT: '/auth/logout',
    CHANGE_PASSWORD: '/auth/change-password',
    RESET_PASSWORD_REQUEST: '/auth/reset-password-request',
    VERIFY_RESET_CODE: '/auth/verify-reset-code',
    RESET_PASSWORD: '/auth/reset-password',
    SETTINGS: '/auth/settings',
    EDUCATIONAL_OPTIONS: '/auth/educational-options',
  },
  TEACHER: {
    QUESTIONS: '/teacher/questions',
    QUESTIONS_TEMPLATE: '/teacher/questions/template',
    QUESTIONS_IMPORT_PREVIEW: '/teacher/questions/import-preview',
    QUESTIONS_IMPORT_CONFIRM: '/teacher/questions/import-confirm',
    EXAMS: '/teacher/exams',
    COMPETITIONS: '/teacher/competitions',
    LESSONS: '/teacher/lessons',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    REPORTS: '/admin/reports',
    REPORTS_ANALYTICS: '/admin/reports/analytics',
    NOTIFICATIONS: '/admin/notifications',
    SUBJECTS: '/admin/subjects',
    UNITS: '/admin/units',
    GRADE_LEVELS: '/admin/grade-levels',
    GRADE_LEVEL_SUBJECTS: (id: number | string) => `/admin/grade-levels/${id}/subjects`,
    GRADE_LEVEL_ASSIGN: (id: number | string) => `/admin/grade-levels/${id}/assign-subjects`,
  },
} as const;
